name: Check Protobuf
on: [push, pull_request]
jobs:
  check-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: JRMurr/direnv-nix-action@v4.1.0
      - name: generate protobuf
        run: go generate .
      - name: check if protobuf files are up to date
        run: git diff --exit-code
